### ISSUE TITLE
Shapeshifting metrics

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/odo#3]
- [ ] Record quits from the retry logic to Prometheus
- [ ] Record relevant happy path metrics in Prometheus

To visualize geospatial datasets in the UI, we need to serve GeoJSON from the API. Most of our geospatial datasets will be ingested as Shapefiles, so we need to convert from Shapefile to GeoJSON.

**Comment by jdenen** [comment]
See #2 about "quits" in the retry logic

**Comment by abrock-accenture** [comment]
BLOCKED
